-- Questão 01. Crie as contas de usuário User_A, User_B, User_C, User_D e User_E
CREATE USER User_A WITH PASSWORD = '123456789!Ab';
CREATE USER User_B WITH PASSWORD = '123456789!Ab';
CREATE USER User_C WITH PASSWORD = '123456789!Ab';
CREATE USER User_D WITH PASSWORD = '123456789!Ab';
CREATE USER User_E WITH PASSWORD = '123456789!Ab';

-- Questão 02. Considere o esquema de banco de dados relacional university
-- O User_A poderá selecionar ou modificar qualquer relação, exceto CLASSROOM, e pode conceder qualquer um desses privilégios a outros usuários.

GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.STUDENT TO User_A WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.INSTRUCTOR TO User_A WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.COURSE TO User_A WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.TAKES TO User_A WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.TEACHES TO User_A WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.DEPARTMENT TO User_A WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.PREREQ TO User_A WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.SECTION TO User_A WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.ADVISOR TO User_A WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.TIME_SLOT TO User_A WITH GRANT OPTION;

-- Questão 03. Liste as permissões do User_A
SELECT 
    'User_A' AS Usuario,
    OBJECT_NAME(major_id) AS Objeto, 
    permission_name AS Permissao
FROM sys.database_permissions 
WHERE grantee_principal_id = USER_ID('User_A');
